/**
 * Mock 题库：5 学科 × 10 题 = 50 题。
 *
 * 错题（errored: true）13 道，分布满足 weeklyTrend = [W1: 4, W2: 5, W3: 3, W4: 1] = 13。
 * 错题带 goal/stepDiagnosis/closingLine/examWeightLabel 等手写叙事字段，被 selector 选中后直接进 FocusPick。
 * 对题（errored: false）只有基本字段，仅用于总数与 KP 频次统计。
 *
 * 周界（"今天"按 2026-05-08 算）：
 *   W1: 04-13 — 04-19   W2: 04-20 — 04-26   W3: 04-27 — 05-03   W4: 05-04 — 05-08
 */

export type MockQuestion = {
  id: string
  subject: string
  date: string // ISO YYYY-MM-DD
  fileName: string
  errored: boolean
  knowledgePoints: string[]
  excerpt: string
  // 仅 errored 时使用，进 FocusPick 的叙事字段
  goal?: string
  stepDiagnosis?: string
  closingLine?: string
  examWeightLabel?: string
}

export const MOCK_QUESTION_BANK: MockQuestion[] = [
  // ─────────── 数学（10：4 错 + 6 对）───────────
  {
    id: "数学-01",
    subject: "数学",
    date: "2026-04-15",
    fileName: "数学-错题-2026-04-15.png",
    errored: true,
    knowledgePoints: ["二次函数顶点式", "h-k 符号判断", "顶点坐标推算", "代入法"],
    excerpt: "y = a(x-h)² + k 求顶点 (-2, 3)",
    goal: "你知道 y = a(x-h)² + k 这个式子里，h 和 k 各管什么吗？",
    stepDiagnosis: "你顶点写对了，但 h = -2 写成了 2。这一翻，整道题就走偏了。",
    closingLine: "下次再遇到顶点式——第一步先把 h、k 的符号锁死。",
    examWeightLabel: "期中压轴 18 分",
  },
  {
    id: "数学-02",
    subject: "数学",
    date: "2026-04-22",
    fileName: "数学-错题-2026-04-22.png",
    errored: true,
    knowledgePoints: ["二次函数顶点式", "配方法", "完全平方公式"],
    excerpt: "y = x² - 4x + 1 配方求顶点",
    goal: "把一般式配成顶点式，h 和 k 是怎么从系数推出来的？",
    stepDiagnosis: "配方时 -4x 配成了 (x-2)²，但常数项算错——少减了 4。",
    closingLine: "配方时记着：(x-h)² 展开会多出 h²，要从 c 里减掉它。",
    examWeightLabel: "期中大题 12 分",
  },
  {
    id: "数学-03",
    subject: "数学",
    date: "2026-04-25",
    fileName: "数学-错题-2026-04-25.png",
    errored: true,
    knowledgePoints: ["二次函数顶点式", "h-k 符号判断", "实际问题"],
    excerpt: "桥梁抛物线最高点求解",
    goal: "实际问题里 h、k 各对应到哪个量？",
    stepDiagnosis: "把「高度最大值」对应到了 h 而不是 k，整个建模反了。",
    closingLine: "应用题里：x 是横向，y 是高度。k 永远是高度的极值。",
    examWeightLabel: "应用题 14 分",
  },
  {
    id: "数学-04",
    subject: "数学",
    date: "2026-04-30",
    fileName: "数学-错题-2026-04-30.png",
    errored: true,
    knowledgePoints: ["二次函数顶点式", "h-k 符号判断"],
    excerpt: "选择题：y = (x+3)² - 5 的顶点",
    goal: "(x+3)² 里 h 应该是几？",
    stepDiagnosis: "把 (x+3)² 看成 (x-h)²，h 应该是 -3，但答成了 3。",
    closingLine: "(x+3)² 等价于 (x-(-3))²，h 是 -3，记着取相反。",
    examWeightLabel: "选择题 4 分",
  },
  {
    id: "数学-05",
    subject: "数学",
    date: "2026-04-13",
    fileName: "数学-题-2026-04-13.png",
    errored: false,
    knowledgePoints: ["一元二次方程", "判别式"],
    excerpt: "判别式判断根的情况",
  },
  {
    id: "数学-06",
    subject: "数学",
    date: "2026-04-18",
    fileName: "数学-题-2026-04-18.png",
    errored: false,
    knowledgePoints: ["全等三角形", "SAS"],
    excerpt: "证明两个三角形全等",
  },
  {
    id: "数学-07",
    subject: "数学",
    date: "2026-04-26",
    fileName: "数学-题-2026-04-26.png",
    errored: false,
    knowledgePoints: ["函数图像", "平移变换"],
    excerpt: "y = x² 向右平移 2 个单位",
  },
  {
    id: "数学-08",
    subject: "数学",
    date: "2026-04-30",
    fileName: "数学-题-2026-04-30b.png",
    errored: false,
    knowledgePoints: ["古典概率", "树状图"],
    excerpt: "投两枚硬币求概率",
  },
  {
    id: "数学-09",
    subject: "数学",
    date: "2026-05-02",
    fileName: "数学-题-2026-05-02.png",
    errored: false,
    knowledgePoints: ["不等式组", "解集"],
    excerpt: "解一元一次不等式组",
  },
  {
    id: "数学-10",
    subject: "数学",
    date: "2026-05-07",
    fileName: "数学-题-2026-05-07.png",
    errored: false,
    knowledgePoints: ["圆方程", "切线"],
    excerpt: "圆心 (1,2) 半径 3 的方程",
  },

  // ─────────── 物理（10：6 错 + 4 对）───────────
  {
    id: "物理-01",
    subject: "物理",
    date: "2026-04-23",
    fileName: "物理-错题-2026-04-23.png",
    errored: true,
    knowledgePoints: ["串并联识别", "电压表位置", "电流表读数", "等效电路"],
    excerpt: "电路图判断 R1 和 R2 是串联还是并联",
    goal: "电路图先看什么？是先找电源，还是先看电压表/电流表的位置？",
    stepDiagnosis: "你把并联看成了串联——少看了电压表跨在哪两个点上。整张图一开局就读错了。",
    closingLine: "下次遇到电路图——第一步先把表跨在哪标出来，再判串并联。",
    examWeightLabel: "实验题 12 分",
  },
  {
    id: "物理-02",
    subject: "物理",
    date: "2026-04-28",
    fileName: "物理-错题-2026-04-28.png",
    errored: true,
    knowledgePoints: ["串并联识别", "等效电路", "阻值计算"],
    excerpt: "三个电阻混联求总电阻",
    goal: "混联电路怎么先化简成纯串或纯并？",
    stepDiagnosis: "化简时漏看了一个支路，把 R3 和 R2 当并联——其实 R3 是单独的。",
    closingLine: "化简前先把每个节点画出来，看哪几个电阻共节点。",
    examWeightLabel: "实验题 10 分",
  },
  {
    id: "物理-03",
    subject: "物理",
    date: "2026-05-05",
    fileName: "物理-错题-2026-05-05.png",
    errored: true,
    knowledgePoints: ["串并联识别", "等效电路"],
    excerpt: "选择题：电路图选项判断",
    goal: "电压表跨在 R1 两端时，它在测什么？",
    stepDiagnosis: "选项里 B 和 C 都涉及电压表跨接，你选了 C，但 C 是串联——电压表不应该跨整段。",
    closingLine: "电压表跨哪两个点，那两点之间就是它在测的部分。",
    examWeightLabel: "选填 6 分",
  },
  {
    id: "物理-04",
    subject: "物理",
    date: "2026-04-18",
    fileName: "物理-错题-2026-04-18.png",
    errored: true,
    knowledgePoints: ["单位换算", "浮力", "阿基米德原理"],
    excerpt: "密度从 g/cm³ 换 kg/m³ 求浮力",
    goal: "cm 换 m、g 换 kg 的时候，幂次怎么处理你心里有数吗？",
    stepDiagnosis: "你把密度从 g/cm³ 换到 kg/m³ 时漏乘了 1000，最后算出来差了一个数量级。",
    closingLine: "下次遇到带单位的物理题——先把所有量统一换到 SI 制再列方程。",
    examWeightLabel: "大题 12 分",
  },
  {
    id: "物理-05",
    subject: "物理",
    date: "2026-04-20",
    fileName: "物理-错题-2026-04-20.png",
    errored: true,
    knowledgePoints: ["单位换算", "国际单位制"],
    excerpt: "速度从 km/h 换 m/s",
    goal: "km/h 换 m/s 是除以多少？",
    stepDiagnosis: "你把 36 km/h 换成了 36 m/s，差了 3.6 倍。",
    closingLine: "km/h ÷ 3.6 = m/s。这一步快算两遍验证再列方程。",
    examWeightLabel: "选填 4 分",
  },
  {
    id: "物理-06",
    subject: "物理",
    date: "2026-05-02",
    fileName: "物理-错题-2026-05-02.png",
    errored: true,
    knowledgePoints: ["单位换算", "密度公式"],
    excerpt: "已知 m 和 V 求 ρ，单位是 g/cm³",
    goal: "ρ = m / V 这个公式，单位是怎么搭配的？",
    stepDiagnosis: "m 用了 g，V 用了 m³，结果单位是 g/m³，跟选项里的 g/cm³ 差了 10⁶。",
    closingLine: "ρ 用 g/cm³ 时：m 用 g、V 用 cm³，单位先对齐再算。",
    examWeightLabel: "选填 6 分",
  },
  {
    id: "物理-07",
    subject: "物理",
    date: "2026-04-15",
    fileName: "物理-题-2026-04-15.png",
    errored: false,
    knowledgePoints: ["平面镜成像", "虚像"],
    excerpt: "镜前 30cm 处的像距",
  },
  {
    id: "物理-08",
    subject: "物理",
    date: "2026-04-25",
    fileName: "物理-题-2026-04-25.png",
    errored: false,
    knowledgePoints: ["力的合成", "平行四边形法则"],
    excerpt: "两力夹角 60° 求合力",
  },
  {
    id: "物理-09",
    subject: "物理",
    date: "2026-04-30",
    fileName: "物理-题-2026-04-30.png",
    errored: false,
    knowledgePoints: ["凸透镜", "物距像距"],
    excerpt: "焦距 10cm 的凸透镜成像",
  },
  {
    id: "物理-10",
    subject: "物理",
    date: "2026-05-06",
    fileName: "物理-题-2026-05-06.png",
    errored: false,
    knowledgePoints: ["欧姆定律", "焦耳定律"],
    excerpt: "电阻发热问题",
  },

  // ─────────── 英语（10：2 错 + 8 对）───────────
  {
    id: "英语-01",
    subject: "英语",
    date: "2026-04-13",
    fileName: "英语-错题-2026-04-13.png",
    errored: true,
    knowledgePoints: ["阅读题主旨判断", "段落首尾句", "语篇结构"],
    excerpt: "Reading Passage 1 — 选最佳标题",
    goal: "做主旨题时，你先看哪几句？",
    stepDiagnosis: "你被第二段一句细节吸引，选了细节相关的选项。但首段最后一句已经点题。",
    closingLine: "主旨题先看每段首尾句，再看选项哪个跟首尾句最贴。",
    examWeightLabel: "阅读 6 分",
  },
  {
    id: "英语-02",
    subject: "英语",
    date: "2026-04-24",
    fileName: "英语-错题-2026-04-24.png",
    errored: true,
    knowledgePoints: ["阅读题主旨判断", "段落首尾句"],
    excerpt: "Reading Passage 3 — 选最匹配的标题",
    goal: "段落首尾不匹配时怎么办？",
    stepDiagnosis: "首尾方向不一致，你选了首段方向的选项——但全文重心在尾段。",
    closingLine: "首尾不一致时看全文重心。哪段写得多就以哪段为主。",
    examWeightLabel: "阅读 6 分",
  },
  {
    id: "英语-03",
    subject: "英语",
    date: "2026-04-14",
    fileName: "英语-题-2026-04-14.png",
    errored: false,
    knowledgePoints: ["词汇辨析"],
    excerpt: "辨析 affect 和 effect",
  },
  {
    id: "英语-04",
    subject: "英语",
    date: "2026-04-17",
    fileName: "英语-题-2026-04-17.png",
    errored: false,
    knowledgePoints: ["完形填空", "上下文逻辑"],
    excerpt: "完形填空 第 5 题",
  },
  {
    id: "英语-05",
    subject: "英语",
    date: "2026-04-20",
    fileName: "英语-题-2026-04-20.png",
    errored: false,
    knowledgePoints: ["阅读题细节"],
    excerpt: "细节定位题",
  },
  {
    id: "英语-06",
    subject: "英语",
    date: "2026-04-27",
    fileName: "英语-题-2026-04-27.png",
    errored: false,
    knowledgePoints: ["语法", "时态"],
    excerpt: "现在完成时和一般过去时",
  },
  {
    id: "英语-07",
    subject: "英语",
    date: "2026-05-02",
    fileName: "英语-题-2026-05-02.png",
    errored: false,
    knowledgePoints: ["写作", "议论文结构"],
    excerpt: "议论文开头段写作",
  },
  {
    id: "英语-08",
    subject: "英语",
    date: "2026-05-04",
    fileName: "英语-题-2026-05-04.png",
    errored: false,
    knowledgePoints: ["中译英"],
    excerpt: "句子翻译练习",
  },
  {
    id: "英语-09",
    subject: "英语",
    date: "2026-05-06",
    fileName: "英语-题-2026-05-06.png",
    errored: false,
    knowledgePoints: ["听力", "细节理解"],
    excerpt: "听力 Section A",
  },
  {
    id: "英语-10",
    subject: "英语",
    date: "2026-05-08",
    fileName: "英语-题-2026-05-08.png",
    errored: false,
    knowledgePoints: ["阅读题细节"],
    excerpt: "阅读题—时间细节",
  },

  // ─────────── 化学（10：1 错 + 9 对）───────────
  {
    id: "化学-01",
    subject: "化学",
    date: "2026-04-17",
    fileName: "化学-错题-2026-04-17.png",
    errored: true,
    knowledgePoints: ["化学方程式配平", "原子守恒", "氧原子数"],
    excerpt: "Fe + O₂ → Fe₂O₃ 配平",
    goal: "配平 Fe + O₂ → Fe₂O₃ 这一类，先看哪个原子？",
    stepDiagnosis: "氧原子配平了，但铁原子没动——左边铁个数和右边对不上。",
    closingLine: "金属生成氧化物时：先看金属，再看氧。两边都对齐。",
    examWeightLabel: "选填 4 分",
  },
  {
    id: "化学-02",
    subject: "化学",
    date: "2026-04-12",
    fileName: "化学-题-2026-04-12.png",
    errored: false,
    knowledgePoints: ["元素周期表", "金属活动性"],
    excerpt: "金属活动性顺序",
  },
  {
    id: "化学-03",
    subject: "化学",
    date: "2026-04-19",
    fileName: "化学-题-2026-04-19.png",
    errored: false,
    knowledgePoints: ["酸碱中和", "pH"],
    excerpt: "盐酸 + 氢氧化钠",
  },
  {
    id: "化学-04",
    subject: "化学",
    date: "2026-04-22",
    fileName: "化学-题-2026-04-22.png",
    errored: false,
    knowledgePoints: ["氧化还原"],
    excerpt: "氧化剂还原剂判断",
  },
  {
    id: "化学-05",
    subject: "化学",
    date: "2026-04-26",
    fileName: "化学-题-2026-04-26.png",
    errored: false,
    knowledgePoints: ["质量守恒"],
    excerpt: "反应前后质量比较",
  },
  {
    id: "化学-06",
    subject: "化学",
    date: "2026-04-29",
    fileName: "化学-题-2026-04-29.png",
    errored: false,
    knowledgePoints: ["实验操作", "玻璃仪器"],
    excerpt: "玻璃棒的作用",
  },
  {
    id: "化学-07",
    subject: "化学",
    date: "2026-05-02",
    fileName: "化学-题-2026-05-02.png",
    errored: false,
    knowledgePoints: ["有机物分类"],
    excerpt: "判断有机物类型",
  },
  {
    id: "化学-08",
    subject: "化学",
    date: "2026-05-04",
    fileName: "化学-题-2026-05-04.png",
    errored: false,
    knowledgePoints: ["溶液浓度"],
    excerpt: "求溶液质量分数",
  },
  {
    id: "化学-09",
    subject: "化学",
    date: "2026-05-06",
    fileName: "化学-题-2026-05-06.png",
    errored: false,
    knowledgePoints: ["气体制取"],
    excerpt: "实验室制氧气",
  },
  {
    id: "化学-10",
    subject: "化学",
    date: "2026-05-08",
    fileName: "化学-题-2026-05-08.png",
    errored: false,
    knowledgePoints: ["金属冶炼"],
    excerpt: "高炉炼铁",
  },

  // ─────────── 语文（10：0 错 + 10 对）───────────
  { id: "语文-01", subject: "语文", date: "2026-04-13", fileName: "语文-题-2026-04-13.png", errored: false, knowledgePoints: ["文言文", "实词"], excerpt: "解释加点字" },
  { id: "语文-02", subject: "语文", date: "2026-04-15", fileName: "语文-题-2026-04-15.png", errored: false, knowledgePoints: ["现代文阅读"], excerpt: "概括人物形象" },
  { id: "语文-03", subject: "语文", date: "2026-04-19", fileName: "语文-题-2026-04-19.png", errored: false, knowledgePoints: ["古诗鉴赏"], excerpt: "古诗手法分析" },
  { id: "语文-04", subject: "语文", date: "2026-04-22", fileName: "语文-题-2026-04-22.png", errored: false, knowledgePoints: ["作文", "议论文"], excerpt: "议论文写作" },
  { id: "语文-05", subject: "语文", date: "2026-04-25", fileName: "语文-题-2026-04-25.png", errored: false, knowledgePoints: ["文言文", "虚词"], excerpt: "虚词辨析" },
  { id: "语文-06", subject: "语文", date: "2026-04-28", fileName: "语文-题-2026-04-28.png", errored: false, knowledgePoints: ["现代文阅读", "主题"], excerpt: "概括文章主题" },
  { id: "语文-07", subject: "语文", date: "2026-05-01", fileName: "语文-题-2026-05-01.png", errored: false, knowledgePoints: ["文学常识"], excerpt: "作家作品配对" },
  { id: "语文-08", subject: "语文", date: "2026-05-04", fileName: "语文-题-2026-05-04.png", errored: false, knowledgePoints: ["默写"], excerpt: "古诗文默写" },
  { id: "语文-09", subject: "语文", date: "2026-05-06", fileName: "语文-题-2026-05-06.png", errored: false, knowledgePoints: ["语病修改"], excerpt: "病句改正" },
  { id: "语文-10", subject: "语文", date: "2026-05-08", fileName: "语文-题-2026-05-08.png", errored: false, knowledgePoints: ["综合性学习"], excerpt: "材料分析" },
]
